networks:
  app-network:
    driver: bridge

services:
  app:
    container_name: app
    build:
      context: ./infra/app
      dockerfile: Dockerfile
      args:
        user: LaNocion
        uid: 777
    image: php-laravel-11
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - 5173:5173
    networks:
        - app-network
    volumes:
      - ./:/var/www
    develop:
      watch:
        - action: sync
          path: ./
          target: /var/www/
        - action: rebuild
          path: package.json
          target: /var/www/


  db:
    container_name: pgsql
    build:
      context: ./infra/pgsql
      dockerfile: Dockerfile
    image: pgsql-docker
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./infra/pgsql/script:/docker-entrypoint-initdb.d
      - ./infra/pgsql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network

  nocion-nginx:
    image: nginx:1.19.8-alpine
    container_name: nocion-nginx
    restart: unless-stopped
    tty: true
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./infra/nginx/conf:/etc/nginx/conf.d
    networks:
      - app-network
